/*
    THIS IS A GENERATED FILE
    Changes might be overwritten in the future, edit with caution!
*/

export const Tables = {
	Trips: 'Trips',
	Clients: 'Clients',
	Users: 'Users',
	TaskStages: 'Task Stages',
	TaskLists: 'Task Lists',
	TaskListTemplates: 'Task List Templates',
	TaskInstances: 'Task Instances',
	TaskListTemplatesSafetomodify: 'Task List Templates (Safe to modify)',
	TaskListInstances: 'Task List Instances',
};

export const Columns = {
	"Trips": {
		tripName: {name:`Trip Name`, type:`text`},
		clientIds: {name:`Client`, type:`foreignKey-many`},
		clientName: {name:`Client Name`, type:`lookup`},
		arrivalCity: {name:`Arrival City`, type:`text`},
		longitude: {name:`Longitude`, type:`text`},
		latitude: {name:`Latitude`, type:`text`},
		tripStartDate: {name:`Trip Start Date`, type:`date`},
		tripEndDate: {name:`Trip End Date`, type:`date`},
		notes: {name:`Notes`, type:`multilineText`},
		'hotel-DepositDueDate': {name:`Hotel - Deposit Due Date`, type:`date`},
		hotel-FinalPaymentDate: {name:`Hotel - Final Payment Date`, type:`date`},
		travelAgentIds: {name:`Travel Agent`, type:`foreignKey-many`},
		recordIdfromTravelAgent: {name:`Record ID (from Travel Agent)`, type:`lookup`},
		totalTravellerCount: {name:`Total Traveller Count`, type:`number`},
		recordId: {name:`Record ID`, type:`formula`},
		createdAt: {name:`Created At`, type:`formula`},
		taskListInstanceIds: {name:`Task List Instances`, type:`foreignKey-many`},
		taskInstanceIds: {name:`Task Instances`, type:`foreignKey-many`},
	},
	"Clients": {
		name: {name:`Name`, type:`formula`},
		tripIds: {name:`Trips`, type:`foreignKey-many`},
		tasks: {name:`Tasks`, type:`text`},
		travelAgentIds: {name:`Travel Agent`, type:`foreignKey-many`},
		recordIdfromTravelAgent: {name:`Record ID (from Travel Agent)`, type:`lookup`},
		picture: {name:`Picture`, type:`multipleAttachment`},
		recordId: {name:`Record ID`, type:`formula`},
		firstName: {name:`First Name`, type:`text`},
		lastName: {name:`Last Name`, type:`text`},
		notes: {name:`Notes`, type:`multilineText`},
	},
	"Users": {
		fullName: {name:`Full Name`, type:`text`},
		recordId: {name:`Record ID`, type:`formula`},
		email: {name:`Email`, type:`text`},
		magicLink: {name:`Magic Link`, type:`text`},
		avatar: {name:`Avatar`, type:`multipleAttachment`},
		clientIds: {name:`Clients`, type:`foreignKey-many`},
		clientMultiselectFormula: {name:`Client Multiselect Formula`, type:`formula`},
		clientMultiselect: {name:`Client Multiselect`, type:`multiSelect`},
		tripIds: {name:`Trips`, type:`foreignKey-many`},
		tasks: {name:`Tasks`, type:`text`},
		taskStages: {name:`Task Stages`, type:`text`},
		taskListInstanceIds: {name:`Task List Instances`, type:`foreignKey-many`},
		taskListInstances2Ids: {name:`Task List Instances 2`, type:`foreignKey-many`},
	},
	"Task Stages": {
		name: {name:`Name`, type:`text`},
		taskListsWithMetadataIds: {name:`Task Lists with metadata`, type:`foreignKey-many`},
		ordinal: {name:`Ordinal`, type:`number`},
		color: {name:`Color`, type:`text`},
		taskListTemplatesCopyIds: {name:`Task List Templates copy`, type:`foreignKey-many`},
		taskListTemplatesCopyIds: {name:`Task List Templates copy`, type:`foreignKey-many`},
	},
	"Task Lists": {
		name: {name:`Name`, type:`text`},
		recordId: {name:`Record ID`, type:`formula`},
	},
	"Task List Templates": {
		name: {name:`Name`, type:`text`},
		type: {name:`Type`, type:`select`},
		stage: {name:`Stage`, type:`select`},
		nDate: {name:`N Date`, type:`select`},
		nDateNum: {name:`N Date Num`, type:`number`},
		stagelinkIds: {name:`Stage (Link)`, type:`foreignKey-many`},
		stageOrdinal: {name:`Stage Ordinal`, type:`lookup`},
		stageColor: {name:`Stage Color`, type:`lookup`},
	},
	"Task Instances": {
		name: {name:`Name`, type:`text`},
		type: {name:`Type`, type:`select`},
		stage: {name:`Stage`, type:`select`},
		nDate: {name:`N Date`, type:`select`},
		nDateNum: {name:`N Date Num`, type:`number`},
		stagelinkIds: {name:`Stage (Link)`, type:`foreignKey-many`},
		stageOrdinal: {name:`Stage Ordinal`, type:`lookup`},
		stageColor: {name:`Stage Color`, type:`lookup`},
		travelAgentIds: {name:`Travel Agent`, type:`foreignKey-many`},
		recordIdfromTravelAgent: {name:`Record ID (from Travel Agent)`, type:`lookup`},
		workflowIds: {name:`Workflow`, type:`foreignKey-many`},
		tripName: {name:`Trip Name`, type:`lookup`},
		clientName: {name:`Client Name`, type:`lookup`},
		status: {name:`Status`, type:`select`},
		recordId: {name:`Record ID`, type:`formula`},
		departureDate: {name:`Departure Date`, type:`date`},
		returnDate: {name:`Return Date`, type:`date`},
		startDate: {name:`Start Date`, type:`date`},
		dueDate: {name:`Due Date`, type:`formula`},
		dateCompleted: {name:`Date Completed`, type:`date`},
		taskListInstanceIds: {name:`Task List Instance`, type:`foreignKey-many`},
	},
	"Task List Templates (Safe to modify)": {
		name: {name:`Name`, type:`text`},
		type: {name:`Type`, type:`select`},
		stage: {name:`Stage`, type:`select`},
		nDate: {name:`N Date`, type:`select`},
		nDateNum: {name:`N Date Num`, type:`number`},
		stagelinkIds: {name:`Stage (Link)`, type:`foreignKey-many`},
		stageOrdinal: {name:`Stage Ordinal`, type:`lookup`},
		stageColor: {name:`Stage Color`, type:`lookup`},
	},
	"Task List Instances": {
		name: {name:`Name`, type:`text`},
		recordId: {name:`Record ID`, type:`formula`},
		travelAgentIds: {name:`Travel Agent`, type:`foreignKey-many`},
		departureDate: {name:`Departure Date`, type:`date`},
		returnDate: {name:`Return Date`, type:`date`},
		workflowIds: {name:`Workflow`, type:`foreignKey-many`},
		taskInstanceIds: {name:`Task Instances`, type:`foreignKey-many`},
		workflowId: {name:`Workflow ID`, type:`lookup`},
	},
};
